### PR TITLE
Completly hide function

### PR DESCRIPTION
**Pull request by MikeCoder96**
Added a checkbox to force taskbar to stay hidden and appear only when start key is pressed!

### CODE REVIEW

**Comment by TechStudent11** [comment]
> appear only when start key is pressed!

That kinda sounds annoying.

**Comment by TechStudent11** [comment]
Yes but I don't want to press the start button when I just want to switch windows, open task view, eetc.

**Comment by ekx** [comment]
@TechStudent11 Then simply don't enable that option? Personally I don't use the taskbar to switch windows or open task view. There are keyboard shortcuts for that

**Comment by TechStudent11** [comment]
> @TechStudent11 Then simply don't enable that option?

Looks like I didn't read the PR properly.

> Added a checkbox to force taskbar to stay hidden and appear only when start key is pressed!

hehe sorry.

---

If this does get added then I probably will just disable it. I know that some people use `Alt-Tab` and `Win-Tab` (maybe) to switch Windows so I can see why this would be great for those users.

**Comment by MikeCoder96** [comment]
I don't think this will be added anymore. It almost 9 months since i made the PR...

**Pull request closed without merging**
